### ISSUE TITLE
Include LibreOffice powered by CIB in the catalogue

### ISSUE THREAD

**Issue by deneb-alpha** [italia/publiccode-crawler#97]
LibreOffice powered by CIB is a complete open source desktop productivity solution for       Companies, Organizations and Public Administrations of all sizes willing to deploy LibreOffice with a long term certified support.

The publiccode.yml file for LibreOffice powered by CIB is available here:
https://github.com/cibsoftware/LibreOfficePoweredByCIB-metadata

**Comment by deneb-alpha** [comment]
@libremente any feedback?

**Comment by libremente** [comment]
Hi @deneb-alpha, could you tell us something more regarding that sw? Thanks a lot! cc @biancini

**Comment by deneb-alpha** [comment]
> Hi @deneb-alpha, could you tell us something more regarding that sw? Thanks a lot! cc @biancini

LibreOffice powered by CIB is the Long Term Support version of LibreOffice directly provided and developed by CIB. CIB is one of the LibreOffice ecosystem contributors that is developing and contributing to the main LibreOffice project and is also providing certified support, custom integrations, trainings and consultancy on LibreOffice.
Always on the public code - public money point of view, and in compliance to the LibreOffice license, CIB is making available the changes made to the code and the new features implemented. 
Please, let me know if you need of more information.

**Comment by deneb-alpha** [comment]
@libremente @biancini do you have any update on this?

**Comment by deneb-alpha** [comment]
hi @biancini, @libremente, @alranel. Could you please tell me if there's something wrong with this PR?

**Comment by deneb-alpha** [comment]
Just for reference: https://github.com/italia/developers-italia-backend/pull/102

**Comment by deneb-alpha** [comment]
the software is still not listed.
